
package cabservice;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.*;
/**
 *
 * @author Vikas Yadav
 */
public class Add_City extends javax.swing.JFrame {
 Dbconn db;
   String url ,city;
  int count=1;
   Graphics g;
    /** Creates new form Add_City */
    public Add_City() {
         db= new Dbconn();
        initComponents();
        
      //  jPanel2.setVisible(false);
        city=JOptionPane.showInputDialog("enter the city");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setToolTipText("Click here to Add City");
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jLabel2.setText("LandMark 2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel3.setText("Distance(KM)");

        jLabel1.setText("LandMark 1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jButton1.setText("Add Path");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CITY");

        jButton2.setText("Complete adding city");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
         int x=evt.getX();
        int y=evt.getY();
        String place=JOptionPane.showInputDialog("enter the Land Mark");
        g=jPanel1.getGraphics();
        g.fillOval(x, y, 10, 10);
        g.drawString(place, x-10, y-10);
        
       String url="insert into city_description "+" values('"+city+"','"+place+"',"+x+","+y+")";
       db.executeupdate(url);
       
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jComboBox1.removeItem("Select");
         jComboBox2.removeItem("Select");
        
        Dbconn db=new Dbconn();
    
            String url="select LandMark from city_description where Name_of_city ='"+city+"'";
        db.executequery(url);
     try{ while(db.rs.next()){
        String str=db.rs.getString("LandMark").trim();
     jComboBox1.addItem(str);
     jComboBox2.addItem(str);
    
     } 
   //  jPanel2.setVisible(true);
     if(count==1){
     Dbconn db1=new Dbconn();
     db1.executequery("select * from city_description where Name_Of_City='"+city+"'");
     g=jPanel1.getGraphics();
      while (db1.rs.next())
        {
            String land=db1.rs.getString(2).trim();
            int x=Integer.parseInt(db1.rs.getString(3));
            int y=Integer.parseInt(db1.rs.getString(4));
            
            g.fillOval(x, y, 10, 10);
            g.drawString(land, x-10, y-10);
        }
     count++;}
     }catch(SQLException e){System.out.println(e.getMessage());}
//     
//    
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//           try{
//            
//            url= "jdbc:odbc:vehicle";
//       
//      
//           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//                   
//       }catch(ClassNotFoundException e)
//       {
//           System.out.println(e.getMessage()+ e.getStackTrace());
//       }
//       try{
//       Connection con=DriverManager.getConnection(url,"root","root@root");
//      Statement  s=con.createStatement();
//          PreparedStatement ps=con.prepareStatement("insert into Path values(?,?,?)");
//                    ps.setString(1,jComboBox1.getSelectedItem().toString());
//                    ps.setString(2, jComboBox2.getSelectedItem().toString());
//                     ps.setString(3, jTextField1.getText());
//                      ps.executeUpdate();
//                         
////                        
//       
//       Graphics gg=jPanel1.getGraphics();
//       ResultSet rs=s.executeQuery("select * from city_description where LandMark='"+jComboBox1.getSelectedItem().toString()+"'" );
//       rs.next();
//       int x1=Integer.parseInt(rs.getString(3));
//       int y1=Integer.parseInt(rs.getString(4));
//       
//        rs=s.executeQuery("select * from city_description where LandMark='"+jComboBox1.getSelectedItem().toString()+"'" );
//       rs.next();
//       int x2=Integer.parseInt(rs.getString(3));
//       int y2=Integer.parseInt(rs.getString(4));
//       gg.drawLine(x1,y1,x2,y2);
//       
                        //Graphics2D ggg= (Graphics2D)jPanel1.getGraphics();
           
            try{
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con = DriverManager.getConnection("jdbc:odbc:vehicle","root","root@root");
        Statement s2 = con.createStatement();
      
        ResultSet rs2 =s2.executeQuery("select * from city_description where Name_Of_City='"+city+"' AND LandMark='"+jComboBox1.getSelectedItem().toString()+"'");
        int x1=0,x2=0,y1=0,y2=0;
                      
                        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase(jComboBox2.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(rootPane, "Both city1 and city2 are same");
        }
        
        
        rs2.next();
         x1=rs2.getInt(3);
         y1=rs2.getInt(4);
      
        
        rs2=s2.executeQuery("select * from city_description where Name_Of_City='"+city+"' AND LandMark='"+jComboBox2.getSelectedItem().toString()+"'");
        rs2.next();
        x2=rs2.getInt(3);
                System.out.println(x1+" "+x2+" "+y1+" "+y2);
                y2=rs2.getInt(4);
       
             if(x1*x2*y2*y1>0){
            System.out.println(4);
             Graphics ggg=jPanel1.getGraphics();
            ggg.setColor(Color.BLACK);
            ggg.drawLine(x1+5, y1+5, x2+5, y2+5);
             ggg.drawString(jTextField1.getText(),(x1+x2)/2, (y1+y2)/2);
             }
            
   PreparedStatement ps=con.prepareStatement("insert into path values(?,?,?,?)");
                    ps.setString(1,jComboBox1.getSelectedItem().toString());
                    ps.setString(2, jComboBox2.getSelectedItem().toString());
                     ps.setString(3, jTextField1.getText());
                     ps.setString(4, city);
        
                      ps.executeUpdate();
            }catch(Exception e){System.out.println(e.getMessage());}    
       
        
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_City.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_City.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_City.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_City.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Add_City().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
